[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Environment variables needed for deployment:
# NEXT_PUBLIC_API_BASE - Your backend API URL (e.g., https://your-backend.onrender.com)
# NEXT_PUBLIC_SOCKET_URL - Your Socket.IO server URL (same as backend)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
