services:
  # Backend API Service
  - type: web
    name: chat-app-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAILS
        sync: false

  # Frontend Service
  - type: web
    name: chat-app-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        sync: false
      - key: NODE_ENV
        value: production
